/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_CFNotificationSource */

#ifndef _Included_bits_hidpunk_osx_CFNotificationSource
#define _Included_bits_hidpunk_osx_CFNotificationSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_CFNotificationSource
 * Method:    createPort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_CFNotificationSource_createPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_CFNotificationSource
 * Method:    destroyPort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_CFNotificationSource_destroyPort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_CFNotificationSource
 * Method:    getLoopSource
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_CFNotificationSource_getLoopSource
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
