/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_EventSourceStruct */

#ifndef _Included_bits_hidpunk_osx_EventSourceStruct
#define _Included_bits_hidpunk_osx_EventSourceStruct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_EventSourceStruct
 * Method:    destruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_EventSourceStruct_destruct
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
