/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_IOIter */

#ifndef _Included_bits_hidpunk_osx_IOIter
#define _Included_bits_hidpunk_osx_IOIter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_IOIter
 * Method:    next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_IOIter_next
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
