/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxHidElement */

#ifndef _Included_bits_hidpunk_osx_OsxHidElement
#define _Included_bits_hidpunk_osx_OsxHidElement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_OsxHidElement
 * Method:    getElementValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidElement_getElementValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidElement
 * Method:    getArrayLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_bits_hidpunk_osx_OsxHidElement_getArrayLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidElement
 * Method:    getArrayElement
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidElement_getArrayElement
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_hidpunk_osx_OsxHidElement
 * Method:    queryElementInfo
 * Signature: (JLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bits_hidpunk_osx_OsxHidElement_queryElementInfo
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
