/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_CFRef */

#ifndef _Included_bits_hidpunk_osx_CFRef
#define _Included_bits_hidpunk_osx_CFRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_CFRef
 * Method:    retain
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_CFRef_retain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_CFRef
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_CFRef_release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
