/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_IOObject */

#ifndef _Included_bits_hidpunk_osx_IOObject
#define _Included_bits_hidpunk_osx_IOObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_IOObject
 * Method:    retain
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_IOObject_retain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_IOObject
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_IOObject_release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
