/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxHidDevice */

#ifndef _Included_bits_hidpunk_osx_OsxHidDevice
#define _Included_bits_hidpunk_osx_OsxHidDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_OsxHidDevice
 * Method:    getHidDictionary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidDevice_getHidDictionary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidDevice
 * Method:    getUsbDictionary
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidDevice_getUsbDictionary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidDevice
 * Method:    queryDeviceInfo
 * Signature: (JJJLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidDevice_queryDeviceInfo
  (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

/*
 * Class:     bits_hidpunk_osx_OsxHidDevice
 * Method:    openInterface
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidDevice_openInterface
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
