/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxHidInterface */

#ifndef _Included_bits_hidpunk_osx_OsxHidInterface
#define _Included_bits_hidpunk_osx_OsxHidInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_OsxHidInterface
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidInterface_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidInterface
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidInterface_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidInterface
 * Method:    getElementValue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_bits_hidpunk_osx_OsxHidInterface_getElementValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bits_hidpunk_osx_OsxHidInterface
 * Method:    getElementEvent
 * Signature: (JILbits/hidpunk/HidEvent;)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidInterface_getElementEvent
  (JNIEnv *, jobject, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
