/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_NotificationHandler */

#ifndef _Included_bits_hidpunk_osx_NotificationHandler
#define _Included_bits_hidpunk_osx_NotificationHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_hidpunk_osx_NotificationHandler_CODE_MATCHED
#define bits_hidpunk_osx_NotificationHandler_CODE_MATCHED 1L
#undef bits_hidpunk_osx_NotificationHandler_CODE_TERMINATED
#define bits_hidpunk_osx_NotificationHandler_CODE_TERMINATED 2L
#undef bits_hidpunk_osx_NotificationHandler_CODE_ERROR
#define bits_hidpunk_osx_NotificationHandler_CODE_ERROR 3L
/*
 * Class:     bits_hidpunk_osx_NotificationHandler
 * Method:    allocateStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_NotificationHandler_allocateStruct
  (JNIEnv *, jclass);

/*
 * Class:     bits_hidpunk_osx_NotificationHandler
 * Method:    initStruct
 * Signature: (JLbits/hidpunk/osx/NotificationHandler;)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_NotificationHandler_initStruct
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     bits_hidpunk_osx_NotificationHandler
 * Method:    freeStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_NotificationHandler_freeStruct
  (JNIEnv *, jclass, jlong);

/*
 * Class:     bits_hidpunk_osx_NotificationHandler
 * Method:    addFoundNotification
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_NotificationHandler_addFoundNotification
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     bits_hidpunk_osx_NotificationHandler
 * Method:    addRemovedNotification
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_bits_hidpunk_osx_NotificationHandler_addRemovedNotification
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
