/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxHidMatcher */

#ifndef _Included_bits_hidpunk_osx_OsxHidMatcher
#define _Included_bits_hidpunk_osx_OsxHidMatcher
#ifdef __cplusplus
extern "C" {
#endif
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_USAGE_PAGE
#define bits_hidpunk_osx_OsxHidMatcher_KEY_USAGE_PAGE 1L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_USAGE
#define bits_hidpunk_osx_OsxHidMatcher_KEY_USAGE 2L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_TRANSPORT
#define bits_hidpunk_osx_OsxHidMatcher_KEY_TRANSPORT 3L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_VENDOR_ID
#define bits_hidpunk_osx_OsxHidMatcher_KEY_VENDOR_ID 4L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_PRODUCT_ID
#define bits_hidpunk_osx_OsxHidMatcher_KEY_PRODUCT_ID 5L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_VERSION_NUM
#define bits_hidpunk_osx_OsxHidMatcher_KEY_VERSION_NUM 6L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_VENDOR_NAME
#define bits_hidpunk_osx_OsxHidMatcher_KEY_VENDOR_NAME 7L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_PRODUCT_NAME
#define bits_hidpunk_osx_OsxHidMatcher_KEY_PRODUCT_NAME 8L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_SERIAL_NUM
#define bits_hidpunk_osx_OsxHidMatcher_KEY_SERIAL_NUM 9L
#undef bits_hidpunk_osx_OsxHidMatcher_KEY_LOCATION_ID
#define bits_hidpunk_osx_OsxHidMatcher_KEY_LOCATION_ID 10L
/*
 * Class:     bits_hidpunk_osx_OsxHidMatcher
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxHidMatcher_create
  (JNIEnv *, jclass);

/*
 * Class:     bits_hidpunk_osx_OsxHidMatcher
 * Method:    setLongValue
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidMatcher_setLongValue
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxHidMatcher
 * Method:    setStringValue
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxHidMatcher_setStringValue
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
