/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxQueue */

#ifndef _Included_bits_hidpunk_osx_OsxQueue
#define _Included_bits_hidpunk_osx_OsxQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    allocateQueue
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_bits_hidpunk_osx_OsxQueue_allocateQueue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    startQueue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxQueue_startQueue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    stopQueue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxQueue_stopQueue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    clearQueue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxQueue_clearQueue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    addElement
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxQueue_addElement
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     bits_hidpunk_osx_OsxQueue
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_bits_hidpunk_osx_OsxQueue_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
