/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class bits_hidpunk_osx_OsxUtil */

#ifndef _Included_bits_hidpunk_osx_OsxUtil
#define _Included_bits_hidpunk_osx_OsxUtil
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
